export const Logos = [
    './clients-logo/Bio Med.webp',
    './clients-logo/BMW.webp',
    './clients-logo/Campilar.webp',
    './clients-logo/Casa Aparecida.webp',
    './clients-logo/Casa da Lavoura.webp',
    './clients-logo/CDL Ji-Paraná.webp',
    './clients-logo/Cinebras.webp',
    './clients-logo/ClickNet.webp',
    './clients-logo/Dr. Alvaro Gaovão.webp',
    './clients-logo/Dr. Renan Helmer.webp',
    './clients-logo/Ellus.webp',
    './clients-logo/Fênix Net.webp',
    './clients-logo/Fórmula X.webp',
    './clients-logo/GNIC.webp',
    './clients-logo/Jeep.webp',
    './clients-logo/Laboratório Padrão.webp',
    './clients-logo/Magrass.webp',
    './clients-logo/Massey Ferguson.webp',
    './clients-logo/Mega Farma.webp',
    './clients-logo/Mercedes.webp',
    './clients-logo/Milenium.webp',
    './clients-logo/Millenium.webp',
    './clients-logo/Mirandex.webp',
    './clients-logo/Onda Ágil.webp',
    './clients-logo/Preço Baixo.webp',
    './clients-logo/Rei do piso.webp',
    './clients-logo/RioBeef.webp',
    './clients-logo/Rondobras.webp',
    './clients-logo/Sal da terra.webp',
    './clients-logo/Snack Saudável.webp',
    './clients-logo/Supremax.webp',
    './clients-logo/Total Lub.webp',
    './clients-logo/Toyota.webp',
    './clients-logo/Unicem.webp',
    './clients-logo/UniCesumar.webp',
    './clients-logo/Vibrágua.webp',
    './clients-logo/West Fire.webp',
]